<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUndoneForms($current_user_id){
        $em = $this->getEntityManager();
        return $em->createQuery('select f from AppBundle:Formation f where ((select count(s) from AppBundle:Score s where s.formidScore = f.formId and IDENTITY(s.userScore) = :curuser) = 0 or (select max(s1.pts) from AppBundle:Score s1 where s1.formidScore = f.formId and IDENTITY(s1.userScore) = :curuser) < 70)')
            ->setParameter('curuser',$current_user_id)
            ->getResult();
    }
}
