security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:  ROLE_USER
        ROLE_SUPERVISOR:  ROLE_USER


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:

            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path:     /

            logout:       ~
            anonymous:    ~


    access_control:
        - { path: ^/login$, allow_if: "is_anonymous() and !is_authenticated()"}
        - { path: ^/$, role: ROLE_USER }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/forms/add, role: ROLE_SUPERVISOR }
        - { path: ^/content/add, role: ROLE_SUPERVISOR }
        - { path: ^/questions/add, role: ROLE_SUPERVISOR }
        - { path: ^/evaluation, role: ROLE_SUPERVISOR }
        - { path: ^/admin/management/, role: ROLE_ADMIN }

